name: Bug报告 | Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        **感谢您的反馈！| Thanks for taking the time to fill out this bug report!**
            请先查找是否已有类似的 [问题](https://github.com/rss-translator/RSS-Translator/issues) 
              Please search [issue](https://github.com/rss-translator/RSS-Translator/issues) before asking
  - type: input
    id: version
    attributes:
      label: 版本号 | Version
      description: What version of our extension are you running?
      placeholder: 2024.5.1
    validations:
      required: true
  - type: input
    id: feed_url
    attributes:
      label: 源地址 | Feed URL
      placeholder: https://example.com/rss.xml
  - type: textarea
    id: describe
    attributes:
      label: 请描述这个Bug | Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
 
