version: '3'
services:
  rsstranslator:
    image: rsstranslator/rsstranslator
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
    volumes:
      - ./data:/home/rsstranslator/data
    ports:
      - 8000:8000
    restart: always
    command: bash -c "python manage.py init_server && python manage.py run_huey & uvicorn config.asgi:application --host 0.0.0.0"